import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { bigintTransformer } from '../../../common/money/money';

export const ACCOUNT_TYPES = ['USER_WALLET', 'SYSTEM_FUNDING', 'SYSTEM_FEES'] as const;
export type AccountType = (typeof ACCOUNT_TYPES)[number];
export type SystemAccountType = Exclude<AccountType, 'USER_WALLET'>;

export const ACCOUNT_STATUSES = ['ACTIVE', 'FROZEN', 'CLOSED'] as const;
export type AccountStatus = (typeof ACCOUNT_STATUSES)[number];

@Entity({ name: 'accounts' })
export class Account {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** Owner; null for system accounts. */
  @Column({ name: 'user_id', type: 'uuid', nullable: true })
  userId!: string | null;

  /** Human-readable number generated by the database (e.g. 1000-0000-0042). */
  @Column({ type: 'varchar', length: 20, default: () => 'next_account_number()' })
  number!: string;

  @Column({ type: 'varchar', length: 50, nullable: true })
  alias!: string | null;

  @Column({ type: 'varchar', length: 20 })
  type!: AccountType;

  @Column({ type: 'char', length: 3, default: 'COP' })
  currency!: string;

  /**
   * Materialized balance in minor units, updated only by LedgerService in the
   * same transaction as the ledger lines. The ledger remains the source of truth.
   */
  @Column({
    name: 'balance_minor',
    type: 'bigint',
    default: () => '0',
    transformer: bigintTransformer,
  })
  balanceMinor!: bigint;

  @Column({ type: 'varchar', length: 20, default: 'ACTIVE' })
  status!: AccountStatus;

  @Column({ type: 'int', default: 0 })
  version!: number;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;
}
